### ISSUE TITLE
Support for partial content requests

### ISSUE THREAD

**Issue by gregogun** [textury/arlocal#109]
When playing back audio (queried from arlocal) in the native html `<audio />` element, although playback is working fine, there seems to be an issue with seeking the audio as no there is no Content-Range header on the response. Using the default `arweave.net` gateway, seeking is working fine.

Just wondering if you have any plans to support this feature anytime soon :)

**Comment by cedriking** [comment]
Solved on `v1.1.41` @gregogun . Thanks @fuadop 🙌🏼

**Comment by gregogun** [comment]
Wow, thanks @fuadop for the quick response much appreciated 🚀🙏
