### ISSUE TITLE
POST /tx 413

### ISSUE THREAD

**Issue by iupii** [textury/arlocal#117]
When trying to upload 1mb file get POST 413.
I found https://github.com/textury/arlocal/blob/06624ab20890707cfe03f47c955cad11835875ef/src/routes/transaction.ts#L130-L134
and didn't find 413, so it looks like some third party code is not ready do get big files.

**Comment by fuadop** [comment]
did you get any logs on arlocal? arlocal do log stuffs on the console whenever there is some sort of error?

**Comment by iupii** [comment]
Just
[7/4/2022, 5:38:03 PM]   xxx POST /tx 413 2ms -
[7/4/2022, 5:38:04 PM]   <-- POST /tx
[7/4/2022, 5:38:04 PM]   xxx POST /tx 413 0ms -
[7/4/2022, 5:38:05 PM]   <-- POST /tx
[7/4/2022, 5:38:05 PM]   xxx POST /tx 413 0ms -
[7/4/2022, 5:38:06 PM]   <-- POST /tx
[7/4/2022, 5:38:06 PM]   xxx POST /tx 413 0

Looks like lib which handle http request has some limits

**Comment by fuadop** [comment]
hmm, for large files, txs are always posted in chunks with the /chunk endpoint. If that's the case, I'll have to try arloader to debug and try to fix this. this might be a bug. truly about the HTTP request handler of arlocal.

**Comment by fuadop** [comment]
A PR has been raised for this, hopefully, it fixes the issue. Thanks for noticing this bug @iupii :heart:

**Comment by iupii** [comment]
Works. Thanks!
