### ISSUE TITLE
Transaction fee calculation

### ISSUE THREAD

**Issue by Retamogordo** [textury/arlocal#126]
Hi,
I noticed that on 18 Nov 2021 src/routes/transaction.ts was refactored in such a way that transaction fee is calculated 
roughly by (data.data_size * 1965132).
My app airdrops winston relying on arweave.transaction.getPrice(...) which yields a value more than ten times smaller than calculated by arlocal, so my transaction fails with status 410.
There is also online arweave fee calculator that yields yet another value.
So I'm confused of what is going on.
Is there a source of truth or a paper I could consult regarding this question ?

**Comment by fuadop** [comment]
Hey @Retamogordo 👋
This is currently outdated, the latest arlocal version uses calculation based on https://arweavefees.com

**Comment by Retamogordo** [comment]
Hi, thanks.
 I'm still confused. This code is still there, I can see it on the latest version of transactions.ts.
And another thing (possibly not related to the former one) is that price requests return different values depending on what provider is queried, e.g.:
 https://arweave.dev/price/400 => returns 65595508 (plain format)
http://localhost:1984/price/400 => returns 26238203 (json)

**Comment by Retamogordo** [comment]
At first glance (I forked the repo today):
in app.ts:
quering price uses this:     
              this.router.get('/price/:bytes/:addy?', async (ctx) => (ctx.body = (+ctx.params.bytes / 1000) * 65595508));

while post transaction code uses another formula to check if balance is sufficient:
 async function txPostRoute(ctx: Router.RouterContext) {
    ....
    const calculatedReward = +(data.data_size || '0') * 1965132;
    if (!wallet || wallet.balance < calculatedReward) {
      ctx.status = 410;
      ctx.body = { code: 410, msg: "You don't have enough tokens" };
      return;
    }

So my tx fails due to insufficient balance, despite I airdrop winston according to price query.

 }

**Comment by Retamogordo** [comment]
Ouch..
So could you somehow inform me as soon as it is fixed ? I mean when it is ready for install at npm. 
Thanks a lot.

**Comment by fuadop** [comment]
Sure !, A PR has been raised on #127. I'll be sure to notify you when npm gets updated with this change.

**Comment by Retamogordo** [comment]
Hi, it's me again,
I see that the fixed is merged, so query results must be consistent.
There is one thing I still do not catch, though.
On https://arweavefees.com/ I notice that they use a kind of step function for fee calculations, 
namely I get the same results for data sizes of, let us say: 400 bytes and 1000 bytes or 4000 bytes, which is 64958659 winston.
Contrary to that ArLocal uses a linear function on data size for fee calc, so for 400 bytes I get 28402855 winston.
So I still observe a certain inconsistency of the two approaches.

**Comment by cedriking** [comment]
Hey @Retamogordo , what @fuadop did here is to set the fee at the default from mainnet. Which will give the same fee calculation for 0 bytes.

On mainnet, after a couple of bytes, the fees are completely dynamic, based on many factors that we cannot recreate on arlocal since there's no competition while mining, limits of txs per blocks, etc.

Hope this helps answer why it's different. The fee should be calculated from the arlocal endpoint `/price/:bytes`.
