### ISSUE TITLE
Feature request: ArBundle support

### ISSUE THREAD

**Issue by atticusofsparta** [textury/arlocal#143]
would be great if we could add bundle unpacking to this so we can test bundle uploads.

**Comment by jim-toth** [comment]
there already is you just have to call /mine and any pending bundles will unbundle and be indexed
arbundles uised to unbundle on upload but it was moved to after a /mine call

**Comment by atticusofsparta** [comment]
ah thanks - looks like the problem i was having was unrelated, will close this issue.
