### ISSUE TITLE
Add support for in-memory sqlite db and/or DataDB

### ISSUE THREAD

**Issue by arielmelendez** [textury/arlocal#147]
Presently, the constructor for an ArLocal instance takes a `dbpath` argument that is used in at least 2 ways (but perhaps others as well):
1) to connect to a sqlite db via connect as currently implemented below:
```
export const connect = (dbPath: string): Knex => {
  return knex({
    client: 'sqlite3',
    connection: {
      filename: join(dbPath, 'db.sqlite'),
    },
    useNullAsDefault: true,
  });
};
```
This function, as written, prevents the caller from utilizing the feature of sqlite where passing the filename as `:memory:` provides you with an in-memory database instance. Perhaps it could be modified to allow that special case.

2) to provide a path prefix where transaction data can be written (i.e. via the DataDB class). 

It would be great to be able to opt into (via constructor arguments, which, by the way, would be better as a single object argument rather than positional arguments) either one or both of those capabilities in an in-memory form via one or more existing or new ArLocal constructor arguments.

Happy to provide more context if necessary. Thanks!

**Comment by cedriking** [comment]
Thanks @arielmelendez ! added since version `1.1.62`.
