### ISSUE TITLE
bug(gql): support `minHeight` & `maxHeight` of `0` in graphql

### ISSUE THREAD

**Issue by dtfiedler** [textury/arlocal#148]
Version:
-  Arlocal: `textury/arlocal:v1.1.60`
- NodeJS: `18.17`

Reproduce:
- start arlocal docker image (currently doing so in docker file)
- mine a few blocks (at least one)
- create interactions (block height > 0)
- run the following GQL query

```
query {
  transactions (
      block: { 
          min: 0
          max: 0
      }
      sort: HEIGHT_DESC,
  ) {
      pageInfo {
          hasNextPage
      }
      edges {
          cursor
          node {
              id
              block {
                  id
                  height
                  timestamp
              }
          }
      }
  }
}
```

The result will include interactions with block heights > 0. Alternatively try and filter out interactions based on `min` and older interactions still show.

Looks like[ this null-coalescent operator needs to also allow for](https://github.com/textury/arlocal/blob/main/src/graphql/resolvers.ts#L65-L66) `0` as a potential `min`/`max` value

NodeJS:
```bash
Welcome to Node.js v18.17.0.
Type ".help" for more information.
> 0 || undefined
undefined --> the issue
> 0 ?? undefined;
0
```

**Comment by cedriking** [comment]
Thanks for the PR. Released in version `1.1.63`.
