### ISSUE TITLE
error

### ISSUE THREAD

**Issue by grandfatheryun** [textury/arlocal#15]
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! sqlite3@5.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sqlite3@5.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-14T06_22_21_752Z-debug.log
Install for arlocal@latest failed with code 1

**Comment by kouraf** [comment]
Hello, 
I would like to know what is your `OS` and what `node` version are running ?
