### ISSUE TITLE
unbundled data item are getting their id cleared

### ISSUE THREAD

**Issue by jim-toth** [textury/arlocal#150]
i'm posting a bundle inside a tx to the post route and the bundle is posting but it's replacing the contained data item's id with all As.  i dug into the code and seems to be a bug with arbundles when using `bundle.getIdBy(0)` returns all `A`s.  I can get the proper id by doing `bundle.get(0).id`

**Comment by jim-toth** [comment]
Added PR here #151

**Comment by cedriking** [comment]
PR added in `1.1.64` Thanks @jim-toth !
