### ISSUE TITLE
Node.js: TypeError: ArLocal is not a constructor

### ISSUE THREAD

**Issue by lanceseidman** [textury/arlocal#154]
I have run both yarn and npm install (removing the previous node mods folder) and changed my package.json to the module, but I am still having an issue running the project in node.js using multiple versions from 16.x - 20.x.

```
const arLocal = new ArLocal();
                  ^
TypeError: ArLocal is not a constructor
```

Code:

```
import ArLocal from 'arlocal';

(async () => {
  const arLocal = new ArLocal();
  await arLocal.start();
  await arLocal.stop();
})();
```

I see the default export, so not sure why this wouldn't work.

**Comment by presstube** [comment]
I am facing this.. What was the solution in the end?

**Comment by cedriking** [comment]
Hi @presstube , in order to use ArLocal with JS you can do: `const arLocal = new ArLocal.default();`.

Hope this helps!
