### ISSUE TITLE
A problem with transactions in 1.0.37 version

### ISSUE THREAD

**Issue by hatskier** [textury/arlocal#17]
I've noticed that transaction posting or transaction fetching was broken in the 1.0.37 version.
After some low level debuggin in this project  https://github.com/ppedziwiatr/swc-test I've found out that transaction data changes in a weird way after posting. After switching to 1.0.36 version of arlocal everything works fine.

**Comment by kouraf** [comment]
can you please give me some further details ? 
And what do you mean by weird ? 

thanks for your issue.

**Comment by ppedziwiatr** [comment]
The file encoding seems to be broken in `1.0.37`
![image](https://user-images.githubusercontent.com/84311757/133418882-b4fbb477-fd2d-4ba6-b4cb-b52f961414d2.png)

What we're doing here is deploying Smartweave contract with its initial state (json).
When we then try to read the contract definition - and its initial state - it gives the above error.

The exact same thing works fine on `1.0.36`

**Comment by kouraf** [comment]
Yes, there was a bug but it was related to how we was saving the data, you can find a quick fix [here](https://github.com/textury/arlocal/tree/fixing-data-encoding).

Let me know if there's anything else.
