### ISSUE TITLE
Add types to npm version

### ISSUE THREAD

**Issue by joshbenaron** [textury/arlocal#19]
At the moment you can't use ArLocal with TypeScript.
The package is written in TypeScript so it should be easy to compile the package with types and post to npm

**Comment by joshbenaron** [comment]
I believe you just need to set `declaration: true` in `tsconfig.json` and then recompile.

**Comment by cedriking** [comment]
Thanks @joshbenaron , added during this commit: https://github.com/textury/arlocal/commit/9f04a9fe62e4a95f785a41df1711301efbe88f60
