### ISSUE TITLE
Wrong owner address set in mined transaction

### ISSUE THREAD

**Issue by ppedziwiatr** [textury/arlocal#26]
Hello again :-)

So I've switched to  a `1.0.43` version, the https://github.com/textury/arlocal/issues/24 issue seems to be fixed, but now I have another problem.
I'm running my integration tests for the PSTs and I've noticed that on `1.0.43` the `owner` that is set on a mined transaction is not the same owner that was used to create this transaction:

![image](https://user-images.githubusercontent.com/84311757/133978280-363c50c9-cc6a-4095-a462-e8508720125b.png)

1. Posting interaction transaction (with "transfer" function): transaction owner's wallet address is set to `gmmqRKbMGu6LY6WosOjlkcKt7xjDJG-3VugH-pQDdnQ` in this case

2. Loading the new transaction - the transaction's owner address is set to `qaBAjOAooARGzvjdPfkj30jr0A2RxQ1i5anWQHynOYs` - instead of `gmmqRKbMGu6LY6WosOjlkcKt7xjDJG-3VugH-pQDdnQ`.

Of course this causes the test to fail - basically it seems that the owner in the mined transaction is always set to some random wallet address...

This worked fine in the previous versions.

**Comment by kouraf** [comment]
fixed in #27
