### ISSUE TITLE
Error running Arlocal - Unexpected Token

### ISSUE THREAD

**Issue by layinka** [textury/arlocal#30]
Hello,

I get the error below when i try to run Arlocal. I am currently on windows 10, node v12.18.

`Unexpected token '.'`

**Comment by fuadop** [comment]
Please use node version 16 upwards @layinka

**Comment by cedriking** [comment]
Maybe a good idea to set this in the requirements (package.json) @fuadop 🙌🏼

**Comment by fuadop** [comment]
> Maybe a good idea to set this in the requirements (package.json) @fuadop 🙌🏼 

True!

**Comment by fuadop** [comment]
> Maybe a good idea to set this in the requirements (package.json) @fuadop 🙌🏼 

Would do that

**Comment by layinka** [comment]
Ok thanks, it works now.

By the way, will ArLocal work with Arconnect? How do i connect it, I updated the config on ArConnect , but i am getting Transaction signing error

**Comment by fuadop** [comment]
> Ok thanks, it works now.
> 
> By the way, will ArLocal work with Arconnect? How do i connect it, I updated the config on ArConnect , but i am getting Transaction signing error

@layinka do you mean connecting to arlocal with [arweave](https://www.npmjs.com/package/arweave) ?

**Comment by layinka** [comment]
Hi, Is there a discord channel I can talk to you through? I meant if I want to sign a transaction with ArConnect wallet-------- Original message --------From: Fuad Olatunji ***@***.***>Date: Sat, 25 Sep 2021, 3:07 amTo: textury/arlocal ***@***.***>Cc: layinka ***@***.***>, Mention ***@***.***>Subject: Re: [textury/arlocal] Error running Arlocal - Unexpected Token (#30)

Ok thanks, it works now.
By the way, will ArLocal work with Arconnect? How do i connect it, I updated the config on ArConnect , but i am getting Transaction signing error

@layinka do you mean connecting to arlocal with arweave ?

**Comment by fuadop** [comment]
@layinka Yeah there is.

**Comment by fuadop** [comment]
@layinka 

https://discord.gg/BqSu5wW3

**Comment by layinka** [comment]
I am already on that group. 

Can i chat with you directly

**Comment by fuadop** [comment]
> I am already on that group. 
> 
> Can i chat with you directly

Textury discord - https://discord.gg/8wJsEGjt

Chat with me on discord Fuadop#4198

@layinka
