### ISSUE TITLE
npx arlocal throws error

### ISSUE THREAD

**Issue by calboru** [textury/arlocal#43]
/.npm/_npx/8250aebdfc72c15b/node_modules/arbundles/build/ar-data-create.js:15
    const _target = opts?.target ? base64url_1.default.toBuffer(opts.target) : null;

              SyntaxError: Unexpected token '.'

**Comment by fuadop** [comment]
Hello @calboru 👋

Please use node >= 16.0.0.

Also check the node version requirements.

**Comment by fuadop** [comment]
A similar issue is at: [issue](https://github.com/textury/arlocal/issues/30). @calboru

**Comment by calboru** [comment]
> Hello @calboru wave
> 
> Please use node >= 16.0.0.
> 
> Also check the node version requirements.

Thank you it worked!

**Comment by fuadop** [comment]
> > Hello @calboru wave
> 
> > 
> 
> > Please use node >= 16.0.0.
> 
> > 
> 
> > Also check the node version requirements.
> 
> 
> 
> Thank you it worked!

Awesome 👏
