### ISSUE TITLE
Latest version gives error when retrieving data that includes tags

### ISSUE THREAD

**Issue by jsoneaday** [textury/arlocal#46]
The specific error is "Cannot return null for non-nullable field Tag.name." There's a sample query below. But when I try using an api I get back all the data when searching by transaction id and it includes the tags as well. I'm using http://localhost:1984/graphql.

```
query {
    transactions(ids: ["<your transaction id>"]) {
        edges {
            node {
                id
                tags {
                  name
                }
            }
        }
    }
}
```
Here's a screenshot of the failure, but to be clear calls work as long as tags are not included. And as I said if I use the api, tags do come back without issue.
![image](https://user-images.githubusercontent.com/1474935/141696811-3a7797c8-8f78-4acf-9478-e12c12c569f1.png)

This is with the tags removed.
![image](https://user-images.githubusercontent.com/1474935/141785496-f9fd2e58-723a-4f36-a664-8ac45f84a9f1.png)

**Comment by fuadop** [comment]
@cedriking @kouraf

**Comment by kouraf** [comment]
@jsoneaday Hi, would you please share with me the tx(s) you added there !

**Comment by cedriking** [comment]
Hey @kouraf it seems that the issue is when not adding a list of txs 🤔 
So you will need to post some txs with tags, and then run the same command he's using:
```graphql
query {
    transactions(ids: ["<your transaction id>"]) {
        edges {
            node {
                id
                tags {
                  name
                }
            }
        }
    }
}
```

**Comment by jsoneaday** [comment]
nWAmogWz_DO4Htzbnw3tH7JqcKu-8nH7IXA2l1YLqGU

But isn't this on my local machine only?

**Comment by kouraf** [comment]
@jsoneaday i mean the data, so i can create the same in my local machine ! :D

**Comment by jsoneaday** [comment]
Do you mean the binary data? This issue occurs with and without the data field being sent anything. Also it occurs with more than one record

![image](https://user-images.githubusercontent.com/1474935/141802011-80d21125-e9d3-45d8-9253-0eade6f5122c.png)

**Comment by kouraf** [comment]
@jsoneaday can we have a call on discord ? my tag is : kouraf#2752

**Comment by kouraf** [comment]
issue related to `arweave-swift`
