### ISSUE TITLE
idea: Implement a "realistic" mode

### ISSUE THREAD

**Issue by noomly** [textury/arlocal#51]
I had an idea for some time to make the usage of arlocal more meaningful: making arlocal more realist by simulating failings.

The blockchain being what it is it's often not so reliable in terms of sending transactions and making sure they succeed. I propose to add an optional functionality to randomly simulate the rejection of transactions, mimicking the behavior of the blockchain. It wouldn't necessarily be that complex to start with, just rejecting some transactions from time to time on a configurable ratio would already be useful. Then maybe trying to iterate on it to make it more realistic and configurable over time. This feature could help to test for resilience in our case and I believe it could also be useful to many others.

How feasible do you think this idea is?

**Comment by fuadop** [comment]
This might be a reference to this feature:

https://github.com/textury/arlocal/pull/56
