### ISSUE TITLE
Make more blockchain info persistent

### ISSUE THREAD

**Issue by noomly** [textury/arlocal#52]
Hey there,

I just learned that it is possible to call the `http://localhost:1984/mine` endpoint to simulate the mining of a block, which could have the potential to extend the way we use this tool to test our platform. However I noticed that the number of block mined isn't persistent, even with the `persistent` option set to true for `new Arweave(...)`, which greatly reduce our use case. Would it be possible to make the information we get at `http://localhost:1984/info` persistent?

**Comment by kouraf** [comment]
this was added to the current version
