### ISSUE TITLE
Cannot write transaction with contract source

### ISSUE THREAD

**Issue by ppedziwiatr** [textury/arlocal#55]
Hey,

I've upgraded ArLocal in our redstone-smartcontracts to the latest version and now during the contract deployment in our intergration tests (eg: https://github.com/redstone-finance/redstone-smartcontracts/blob/main/src/__tests__/integration/deploy-write-read.test.ts) I'm getting an error while creating a transaction with contract source:
`srcTx = await this.arweave.createTransaction({ data: src }, wallet);`

The last version that works properly, is `1.1.9`

**Comment by cedriking** [comment]
Hey @ppedziwiatr we now force the need to add funds to your wallet before being able to send transactions. This is to have more of an accurate local testnet with the mainnet.

**Comment by ppedziwiatr** [comment]
> 

Ok, that makes sense :-)

Tried to fix this by calling the mint endpoint, but I'm still getting an error - can you please suggest what I'm doing wrong? https://github.com/redstone-finance/redstone-smartcontracts/pull/56/files#diff-4c8ef438798c3bfb11da9a1e567605a4ddbce94c7ac1201dc739a65658b353de

**Comment by fuadop** [comment]
Hello @ppedziwiatr , The mint amount is in winston, you minted 1000 winstons, isnt' that too small to create a transaction ?

**Comment by ppedziwiatr** [comment]
Oh crap, you're right, not sure why I assumed that it's in ARs...thanks for clarification!
