### ISSUE TITLE
Cannot start arlocal

### ISSUE THREAD

**Issue by michalko** [textury/arlocal#62]
Hi, try to run arlocal but it doesn't start, it started to happen today:

`PS D:\ar> npx arlocal`
`Need to install the following packages:`
  `arlocal`
`Ok to proceed? (y)`
`npm WARN deprecated noble-ed25519@1.2.6: Switch to namespaced @noble/ed25519 for security and feature updates`
`npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.`
`PS D:\ar>`

Please help, what could that be?

Best

**Comment by fuadop** [comment]
Can you try it without using npx? If it's the same thing @michalko 

1. `npm install -g arlocal@latest` 
2. `arlocal`

**Comment by cedriking** [comment]
Hey there 👋 are you using the latest version 1.1.18 when encountering this error message?

**Comment by michalko** [comment]
Hmm, so when i try to do "npm install -g arlocal@latest" i get error regarding not initialized python env variable:
"Error: Can't find Python executable "python", you can set the PYTHON env variable."

But 1.1.16 works fine, i will try to set python variable and it should work with newest version i guess.

Thank you very much!!

**Comment by gen4sp** [comment]
Confirming. It stops working for me just like 24h ago or so. and I have no idea why,  just quits without any errors.

**Comment by fuadop** [comment]
> Confirming. It stops working for me just like 24h ago or so. and I have no idea why, just quits without any errors.

Yeah, the issue happened after updating knex, seems knex needs to have python installed on the local machine.

for the moment, you can use arlocal@1.1.16. Whilst we get that fixed

And you can try installing python too . Sorry for the inconvenience

**Comment by kouraf** [comment]
Or you can run it using docker 
`docker run -p 1984:1984 textury/arlocal`

**Comment by fuadop** [comment]
> Or you can run it using docker 
> 
> `docker run -p 1984:1984 textury/arlocal`

Yes, exactly 💪. The docker image already have all the necessary dependencies.

**Comment by cedriking** [comment]
Hey @michalko version 1.1.19 has been released with an downgrade of knex. It wont ask again to have python installed.
You can always use `npx arlocal@1.1.19` to test it out.

**Comment by michalko** [comment]
thanks, ill try
