### ISSUE TITLE
Arlocal on node.js [ECONNREFUSED]

### ISSUE THREAD

**Issue by michalko** [textury/arlocal#65]
Hi, 
i want to run arweave transaction on nodejs locally with running arlocal. My arlocal run on http://localhost:1984/.
I initialized arweave as:

```
const arweave = Arweave.init({
  'host': 'localhost',
  'port': 1984,
  'protocol': 'http'
})
```
i'm seding transaction as:

```
let transaction = await arweave.createTransaction({ data: "pipka" })
await arweave.transactions.sign(transaction)
```

I'm getting:
```
(node:213) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:1984
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:213) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
```

Does arweave with arlocal not work on node? Because i copypasted everything from https://edgeandnode.com/blog/developers-guide-to-arweave except the part that my code is in node, and tutorials on react.

Any suggestions would be very appreciated

Best!

**Comment by fuadop** [comment]
Hello @michalko , 

There are a few options to troubleshoot here;
firstly, are you running an arlocal server ?

secondly, I think youre calling the arweave functions wrongly, arweave requires your wallet key to create and sign a transaction

```js
let key = await arweave.wallets.generate();

let transaction = await arweave.createTransaction({
    target: '1seRanklLU_1VTGkEk7P0xAwMJfA7owA1JHW5KyZKlY',
    quantity: arweave.ar.arToWinston('10.5')
}, key);

await arweave.transactions.sign(transaction, key);
```

[arweave-js how to sign a transaction](https://github.com/ArweaveTeam/arweave-js#sign-a-transaction) - https://github.com/ArweaveTeam/arweave-js#sign-a-transaction

**Comment by michalko** [comment]
Thank you, i will check.

**Comment by michalko** [comment]
I tried with generated key and my own installed wallet, but same error happens. I'm running arlocal by running
```
npx arlocal
```
in a terminal:
```
PS C:\Users\michalko\ar> npx arlocal
arlocal started on port 1984
```

i tried with 
```
let key = await arweave.wallets.generate();

let transaction = await arweave.createTransaction({ data: "pipka" }, key)
await arweave.transactions.sign(transaction, key)
```

and also using my wallet by exporting json file from arweave wallet and using it to sign transaction like:

```
  const wallet = JSON.parse(process.env.ARWEAVE_WALLET);

  let transaction = await arweave.createTransaction({ data: "pipka" }, wallet)
  await arweave.transactions.sign(transaction, wallet)
```

but same error.


![image](https://user-images.githubusercontent.com/232871/151709744-f7380707-c42a-4787-bf5c-f568ceea94d7.png)

Best!

**Comment by fuadop** [comment]
Hey @michalko , how are you starting your arlocal server ? 

ERRCONNREFUSED means the server is not started or the server crashed ?

**Comment by fuadop** [comment]
Hey @michalko , can we get on a call ? also can you navigate to http://localhost:1984 on your browser if you get a reponse

**Comment by michalko** [comment]
Hey,

i'm just running 
```
PS C:\Users\michalko\ar> npx arlocal
arlocal started on port 1984
```
like i read in the doc. Do i need to do something else to start it :)? 

i get
```

{
  "network": "arlocal.N.1",
  "version": 1,
  "release": 1,
  "queue_length": 0,
  "peers": 1,
  "height": 0,
  "current": "6vyx3dpj8xsxd6ul9m0ezgbv5odmr3rj23qyuda91uvq2pt182px539sm53tqfch",
  "blocks": 1,
  "node_state_latency": 0
}

```

when i go to http://localhost:1984.

![image](https://user-images.githubusercontent.com/232871/151710073-f2bde0a2-6237-435b-978d-1009ca46dbcc.png)

**Comment by michalko** [comment]
Sure we can call :))

**Comment by fuadop** [comment]
Hey @michalko , send me a message on discord : Fuadop#4198 

join this google meet: https://meet.google.com/owj-orsk-iao

**Comment by michalko** [comment]
It works now. I changed 
```
const Arweave = require('arweave/node');
```
to
```
const Arweave = require('arweave');
```

and it's working.

Thank @fuadop for help.

**Comment by fuadop** [comment]
That's awesome 🎉

**Comment by michalko** [comment]
After all import wasn't the core issue. Core issue was that i was running arlocal from windows terminal like this:

![image](https://user-images.githubusercontent.com/232871/151713025-a8c306c2-49a4-430d-9ff8-ee72f10d0079.png)

and somehow that caused this error:
`
UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:1984
`

when i started arlocal from vscode terminal it somehow works. 
![image](https://user-images.githubusercontent.com/232871/151713093-09513105-88af-4e02-b62e-924e08d3267a.png)


I'm not sure what causes this issue on my laptop but i'm writing it if someone else has this in this future.

**Comment by fuadop** [comment]
Oh wow 
That's weird.

Thanks @michalko 💪🎉

**Comment by michalko** [comment]
ok, for anybody interested, it happened because arlocal was started in windows shell, in linux shell it works fine
