### ISSUE TITLE
GET `/tx/<id>/offset` throws error in bundle context

### ISSUE THREAD

**Issue by handlebauer** [textury/arlocal#72]
Hello,

I notice that, after bundling data, if I try to fetch an individual data item's offset — i.e. using the `/tx/<id>/offset` route — an error is thrown:

```sh
{
  error: TypeError: Cannot read properties of undefined (reading 'offset')
      at null.<anonymous> (node_modules/arlocal/src/routes/transaction.ts:133:33)
      at Generator.next (<anonymous>)
      at fulfilled (/node_modules/arlocal/bin/routes/transaction.js:5:58)
}
```
Alongside an HTTP response body of `OK` (instead of the expected `{ size: number, offset: number }`).

Everything else pertaining to the data item's transaction is just dandy; it's only that route that's giving me problems. Normal (non-bundled) transactions also appear unaffected.

Thanks for looking into this!

**Comment by handlebauer** [comment]
Ah, just realizing regular Arweave nodes behave similarly. Feel free to close if this is expected behaviour.

**Comment by cedriking** [comment]
Thanks @handlebauer , Thanks for letting us know of that error, for now, this is expected for bundle data.
