### ISSUE TITLE
How to query the data stored on Arlocal?

### ISSUE THREAD

**Issue by opmaaadi** [textury/arlocal#82]
Let's say I make some transactions, then I want to retrieve their tags for instance:

```
query {
    transactions {
        edges {
            node {
                id
                tags {
                    name
                    value
                }
            }
        }
    }
}  
```

Above is the GraphQL query I use, Then using a tool like `Insomnia` (or `Postman`), I send a `Post` request to `localhost:1984` (where `Arlocal `is run), but all I get is: `Method Not Allowed`.

I'm a newbie in the blockchain world so I'd be grateful if you could show me what I'm doing wrong.

**Comment by fuadop** [comment]
Hey @opmaaadi 👋,

You have to make graphql requests to the /graphql endpoint (http://localhost:1984/graphql) POST.

**Comment by opmaaadi** [comment]
> Hey @opmaaadi 👋,
> 
> You have to make graphql requests to the /graphql endpoint (http://localhost:1984/graphql) POST.

Hi! Thank you for your response.

Well it returns `500 - Internal Server Error` when hitting /graphql

**Comment by fuadop** [comment]
Did you get an error message on your arlocal logs ? Can you please share the error message.
Also you can try visting the /graphql endpoint in your browser and try the GQL query on the playground.

**Comment by fuadop** [comment]
You can also use [ardb](https://github.com/textury/ardb) to make Arweave GQL queries. It's way easier.

**Comment by fuadop** [comment]
That's awesome @opmaaadi 🚀
