### ISSUE TITLE
Is there a size limit on a /{txId} endpoint?

### ISSUE THREAD

**Issue by ppedziwiatr** [textury/arlocal#83]
Hey,

I'm trying to load a wasm binary file in my integration test. By default our SDK is using the 
`/{txId}` to load the data - if it fails, it falls back to `await this.arweave.transactions.getData`.

In case of this binary (~360kb) - loading it from ArLocal's `/{txId}` and then trying to instantiate a WASM module - ends-up with this error:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/84311757/157746575-2dc8a2e5-b87f-40e7-8e7a-ceefb13684c0.png">

It looks as if the data was truncated / not fully loaded. 

When I load the binary using the `await this.arweave.transactions.getData` - it works properly.

Using ArLocal `1.1.26`

Also - attaching the WASM binary.
[go-pst.wasm.zip](https://github.com/textury/arlocal/files/8226933/go-pst.wasm.zip)

**Comment by fuadop** [comment]
Hey @ppedziwiatr ,

Can I get your test script? Or would I be able to remake this by uploading the wasm with [arkb](https://github.com/textury/arkb)?

**Comment by ppedziwiatr** [comment]
> Hey @ppedziwiatr ,
> 
> Can I get your test script? Or would I be able to remake this by uploading the wasm with [arkb](https://github.com/textury/arkb)?

Hmm, I think I've also found another issues ;-)

1. Issue #1
https://github.com/redstone-finance/redstone-smartcontracts/tree/ppe/arlocal-issue-1

- `clone`, `yarn install`, `yarn jest src/__tests__/integration/internal-writes/staking.test.ts` - tests should pass

Now update in package.json: `arlocal` to `1.1.26` and `arweave-js` to `1.10.23`
Then -  again`yarn install` and `yarn jest src/__tests__/integration/internal-writes/staking.test.ts` - the last test will now fail.
This test deploys the same contract twice. For some reason - while loading the initial state for the second contract - the initial state from the first contract is returned (for `arlocal``1.1.26` and `arweave-js` `1.10.23`)

The data is loaded here: https://github.com/redstone-finance/redstone-smartcontracts/blob/ppe/arlocal-issue-1/src/utils/ArweaveWrapper.ts#L92

2. Issue #2 (original one)
https://github.com/redstone-finance/redstone-smartcontracts/tree/ppe/arlocal-issue-2

- `clone`, `yarn install`, `yarn jest src/__tests__/integration/wasm/go-deploy-write-read.test.ts` - tests should pass.

Now change the implementation of `ArweaveWrapper.txData` method https://github.com/redstone-finance/redstone-smartcontracts/blob/ppe/arlocal-issue-2/src/utils/ArweaveWrapper.ts#L90 to
```ts
  async txData(id: string): Promise<Buffer> {
    // note: this is using arweave.net cache -
    // not very safe and clever, but fast...
    const response = await fetch(`${this.baseUrl}/${id}`);
    if (!response.ok) {
      this.logger.warn(`Unable to load data from arweave.net/${id} endpoint, falling back to arweave.js`);
      // fallback to arweave-js as a last resort..
      const txData = (await this.arweave.transactions.getData(id, {
        decode: true
      })) as Uint8Array;
      return isomorphicBuffer.from(txData);
    } else {
      const buffer = await response.arrayBuffer();
      return isomorphicBuffer.from(buffer);
    }
  }
```

Run `yarn jest src/__tests__/integration/wasm/go-deploy-write-read.test.ts` again - the test will now fail with errors like
`CompileError: WebAssembly.compile(): expected 115 bytes, fell off end @+469238`

**Comment by fuadop** [comment]
Hey @ppedziwiatr , What's issue number 1 about ?

**Comment by ppedziwiatr** [comment]
Hey, re. issue nr 1 - to me it looks that if use `arweave.transactions.getData` to load the data, the ArLocal returns the same data for different transaction ids. This test deploys the same contract - but with different initial states. When I'm trying to load the data for the second contract - the initial state for the first one is returned.

It works fine if I use the `/${id}` endpoint (but using `/${id}` does not work in the second issue - as described there..)

**Comment by fuadop** [comment]
Okay @ppedziwiatr , thanks. You can test on the branch of the Open PR for the second issue fix (the wasm issue).

**Comment by ppedziwiatr** [comment]
> Okay @ppedziwiatr , thanks. You can test on the branch of the Open PR for the second issue fix (the wasm issue).

I can confirm that code from this PR fixes 2nd. issue :-)

**Comment by fuadop** [comment]
Hey @ppedziwiatr , can you test on this new branch. The first issue of same data.

#86

**Comment by ppedziwiatr** [comment]
> Hey @ppedziwiatr , can you test on this new branch (the second linked PR). The first issue of same data.
> 
> #86

It works! 👍
