### ISSUE TITLE
Issue with loading wasm binary on ArLocal 1.1.29

### ISSUE THREAD

**Issue by ppedziwiatr** [textury/arlocal#88]
Hey!

That's probably a followup of https://github.com/textury/arlocal/issues/83

After switching to ArLocal 1.1.29, I'm getting these errors while trying to load wasm binary (using the `/{txId}` endpoint:
<img width="794" alt="image" src="https://user-images.githubusercontent.com/84311757/159678960-5367e4fb-75fa-4164-bfa2-a8c8e3f6e9cf.png">

If I try to load the data with 
```ts
const txData = (await this.arweave.transactions.getData(id, {
      decode: true
    })) as Uint8Array;
```

I'm getting these errors
<img width="970" alt="image" src="https://user-images.githubusercontent.com/84311757/159679160-1a4dd582-c850-4d86-afba-959986a66f79.png">

Originally raised on Discord and reproduced by @kouraf

**Comment by kouraf** [comment]
fixed in #89 :raised_hands:
