### ISSUE TITLE
Wallet not found error

### ISSUE THREAD

**Issue by cedriking** [textury/arlocal#97]
Hey @fuadop , @abhavk is currently having an issue using Arlocal where he funded a wallet address and then used that wallet address to send funds  to another wallet + a contract interaction. Abhav is receiving an error `404 - Wallet not found`.

![image](https://user-images.githubusercontent.com/33100863/164261161-f419333e-cceb-43ca-a252-cf781c381907.png)

Can you please take a look into this. Thanks 🙌🏼

**Comment by fuadop** [comment]
Hi @abhavk, can I get your scripts to replicate this issue ? 🙏🏾

**Comment by abhavk** [comment]
Thanks @fuadop @cedriking, seems like this issue does not exist in later versions, atleast after `1.1.30`. I'll use that going forward, we can close this issue.

**Comment by fuadop** [comment]
Awesome @abhavk
